### ISSUE TITLE
java.lang.runtime.exception when opening zarr

### ISSUE THREAD

**Issue by jingxuanlim** [saalfeldlab/n5-ij#29] opened 2021-03-28 20:58 UTC
Hello.

Great work and many thanks for making this plugin!

I am trying to open a zarr file, but keep running into the following exception.

![image](https://user-images.githubusercontent.com/16644710/112767815-c678fd00-8fe6-11eb-9b47-c73f140ab8e9.png)

I tried it with "Open as virtual" checked and not. Do you know what went wrong?

```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 1000000
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:78)
	at net.imglib2.img.cell.LazyCellImg$LazyCells.get(LazyCellImg.java:104)
	at net.imglib2.img.list.AbstractLongListImg$LongListRandomAccess.get(AbstractLongListImg.java:274)
	at net.imglib2.img.cell.CellRandomAccess.getCell(CellRandomAccess.java:137)
	at net.imglib2.img.cell.CellRandomAccess.updatePosition(CellRandomAccess.java:475)
	at net.imglib2.img.cell.CellRandomAccess.<init>(CellRandomAccess.java:131)
	at net.imglib2.img.cell.AbstractCellImg.randomAccess(AbstractCellImg.java:104)
	at net.imglib2.img.cell.AbstractCellImg.randomAccess(AbstractCellImg.java:51)
	at net.imglib2.util.Util.getTypeFromInterval(Util.java:806)
	at org.janelia.saalfeldlab.n5.ij.N5Importer.read(N5Importer.java:390)
	at org.janelia.saalfeldlab.n5.ij.N5Importer.process(N5Importer.java:510)
	at org.janelia.saalfeldlab.n5.ij.N5Importer.process(N5Importer.java:482)
	at org.janelia.saalfeldlab.n5.ij.N5Importer.process(N5Importer.java:530)
	at org.janelia.saalfeldlab.n5.ij.N5Importer$1.run(N5Importer.java:568)
	at org.janelia.saalfeldlab.n5.ij.N5Importer.processThread(N5Importer.java:571)
	at org.janelia.saalfeldlab.n5.ij.N5Importer.datasetSelectorCallBack(N5Importer.java:297)
	at org.janelia.saalfeldlab.n5.ui.DatasetSelectorDialog.ok(DatasetSelectorDialog.java:542)
	at org.janelia.saalfeldlab.n5.ui.DatasetSelectorDialog.lambda$run$5(DatasetSelectorDialog.java:270)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 1000000
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:145)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:76)
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:74)
	... 53 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1000000
	at net.imglib2.img.basictypeaccess.array.AbstractByteArray.setValue(AbstractByteArray.java:67)
	at net.imglib2.type.numeric.integer.GenericByteType.setByte(GenericByteType.java:135)
	at org.janelia.saalfeldlab.n5.imglib2.N5CellLoader.lambda$createCopy$1(N5CellLoader.java:191)
	at org.janelia.saalfeldlab.n5.imglib2.N5CellLoader.load(N5CellLoader.java:144)
	at net.imglib2.cache.img.LoadedCellCacheLoader.get(LoadedCellCacheLoader.java:124)
	at net.imglib2.cache.img.LoadedCellCacheLoader.get(LoadedCellCacheLoader.java:84)
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:135)
	... 55 more
```

**Comment by bogovicj** [comment] 2021-04-19 17:39
Hi @jingxlim 
Thanks for reporting. I'll look into it.

**Comment by hotzenklotz** [comment] 2021-05-27 12:08
Same happened to me just now. Looking forward to a fix. Thanks.

**Comment by bogovicj** [comment] 2021-12-08 22:18
@jingxlim , @hotzenklotz 

I've had difficulties reproducing this.  Does it always happen with zarr's of a particular size?
Could you post the `.zarray` for a dataset that causes this? I think that will be helpful.

Alternatively, if you have some code that creates data that causes this error, that would be even better.

**Comment by hotzenklotz** [comment] 2021-12-13 14:44
Unfortunately, I can not share the dataset in question since I am not the owner. :-/ 

> Does it always happen with zarr's of a particular size?

The dataset was 110MB so not terribly large.

I am not sure, but maybe the issue could stem from some file format incompatilibties. I believe my file was an OME-Zarr... not sure if those are supported.

**Comment by bogovicj** [comment] 2021-12-14 19:27
Thanks @hotzenklotz that's helpful.

> I believe my file was an OME-Zarr

This could be the issue.  There is now a [new release of n5-zarr](https://github.com/saalfeldlab/n5-zarr/releases/tag/n5-zarr-0.0.7) that will better support OME-Zarr's . This fix will be included in an n5-ij release that I'm preparing right now - hopefully that will do the trick.

**Comment by bogovicj** [comment] 2024-03-06 18:10
I expect the release ~2 years ago fixed this, so am finally closing this.

**Closed by bogovicj** 2024-03-06 18:10 UTC
