### ISSUE TITLE
Feature: Image window name

### ISSUE THREAD

**Issue by ieivanov** [saalfeldlab/n5-ij#21] opened 2021-01-25 00:05 UTC
It would be great if the Fiji image window carries the name of the dataset that is open. Currently all windows are named "(V)" which makes it difficult to navigate multiple open datasets without manually renaming the windows.

**Comment by bogovicj** [comment] 2021-01-25 13:57
This is a bug, and not the intended behavior.
Thanks for reporting.

**Comment by ieivanov** [comment] 2021-01-25 22:39
Update: the ImageJ image window is named correctly as `Group/Array` if the root folder ends with `.zarr` as is the convention. If the root folder does not end with `.zarr`, arrays can still be opened by directly navigating to them, but the image window has a blank name. It would be nice if in that case the window carries the name of the array.

**Comment by bogovicj** [comment] 2021-03-24 20:22
The commit above addresses this, and I havn't observed this issue since, so I'm closing this. 
Thanks again

**Closed by bogovicj** 2021-03-24 20:22 UTC
Labels: bug
